version: 0.2

phases:
  install:
    commands:
      - yum -y update
      - yum -y install python
      - yum -y install python3 
      - yum -y install python-pip
      - yum -y install python3-pip
  pre_build:
    commands: 
      - echo Project is going to be started
      - echo Testing git secrets
      #- docker run gesellix/trufflehog --json https://github.com/tahirjaved1/awscicd.git > trufflehog
      #- cat trufflehog
      # Adding Source Code Analysis COmposition#
      #- wget https://github.com/tahirjaved1/awscicd/blob/master/owasp-dependency-check.sh
      - echo Doing Source Code Analysis
      #- chmod +x /home/ec2-user/owasp-dependency-check.sh
      #- testing 
      # - wget https://raw.githubusercontent.com/tahirjaved1/awscicd/master/source.sh
      # - chmod +x source.sh
      # - bash source.sh
      # - docker pull owasp/dependency-check
      # - DC_VERSION="latest"
      # - DC_DIRECTORY=$HOME/OWASP-Dependency-Check
      # - DC_PROJECT="dependency-check scan:$(pwd)"
      # - DATA_DIRECTORY="$DC_DIRECTORY/data"
      # - CACHE_DIRECTORY="$DC_DIRECTORY/data/cache"
      # - mkdir -p "$DATA_DIRECTORY"
      # - mkdir -p "$CACHE_DIRECTORY"
      # - docker run owasp/dependency-check --rm -e user=$USER -u $(id -u ${USER}):$(id -g ${USER}) --volume $(pwd):/src:z --volume "$DATA_DIRECTORY":/usr share/dependency-check/data:z --volume $(pwd)/odc-reports:/report:z owasp/dependency-check --scan /src --format "ALL" --project "$DC_PROJECT" --out /report
      - rm Vulny-Code-Static-Analysis/ || true
      - git clone https://github.com/swisskyrepo/Vulny-Code-Static-Analysis
      - cd Vulny-Code-Static-Analysis/
      # - sudo chmod +x index.py
      # - sudo chmod +x detection.py
      # - sudo chmod + functions.py
      # - sudo chmod +x indicators.py
      - python3 index.py -h
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
artifacts:
  files:
    - '**/*'