version: 0.2

phases:
  pre_build:
    commands: 
      - echo Project is going to be started
      - echo Testing git secrets
      #- docker run gesellix/trufflehog --json https://github.com/tahirjaved1/awscicd.git > trufflehog
      #- cat trufflehog
      # Adding Source Code Analysis COmposition#
      #- wget https://github.com/tahirjaved1/awscicd/blob/master/owasp-dependency-check.sh
      - echo Doing Source Code Analysis
      #- chmod +x /home/ec2-user/owasp-dependency-check.sh
      #- testing 
      - wget https://raw.githubusercontent.com/tahirjaved1/awscicd/master/source.sh
      - chmod +x source.sh
      - bash source.sh
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
artifacts:
  files:
    - '**/*'