version: 0.2

phases:
  install:
    commands: 
      - echo Project is going to be started
      - echo Testing git secrets
      - bash 'docker run gesellix/trufflehog --json https://github.com/tahirjaved1/awscicd > trufflehog'
      - bash 'cat trufflehog'
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
artifacts:
  files:
    - '**/*'