version: 0.2

phases:
  pre-build:
    commands: 
      - echo Project is going to be started
      - echo Testing git secrets
      - docker run gesellix/trufflehog --json https://github.com/tahirjaved1/awscicd.git
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
artifacts:
  files:
    - '**/*'